# Generated by Django 5.0.6 on 2024-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_mode_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='session',
        ),
        migrations.AddField(
            model_name='mode',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
