# Generated by Django 5.0.6 on 2024-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_type_mode_status_mode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='images/*'),
        ),
    ]
