# Generated by Django 5.0.6 on 2024-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_type_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
