# Generated by Django 5.0.6 on 2024-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_type_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
